apiVersion: v1
kind: Service
metadata:
  name: vip-vllm
  namespace: vllm
  labels:
    app: vllm
    app.kubernetes.io/name: vllm
    app.kubernetes.io/component: inference
  annotations:
    metallb.io/address-pool: vllm-pool
spec:
  type: LoadBalancer
  selector:
    app: vllm
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
